import { randomUUID } from "node:crypto";
import type { PaymentProvider } from "./payment-provider.js";
import type { PaymentRepository } from "./payment-repository.js";
import { evaluatePaymentRisk } from "./payment-risk.js";
import type { SensitiveAuthorization, AuthorizationProof } from "../security/sensitive-authorization.js";
export class PaymentService{
 constructor(private readonly repo:PaymentRepository,private readonly providers:Record<"paystack"|"flutterwave",PaymentProvider>,private readonly authorization?:SensitiveAuthorization){}
 async initialize(input:{userId:string;provider:"paystack"|"flutterwave";amountMinor:number;email:string;callbackUrl?:string}){if(!Number.isSafeInteger(input.amountMinor)||input.amountMinor<=0)throw Error("PAYMENT_AMOUNT_INVALID");if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(input.email))throw Error("PAYMENT_EMAIL_INVALID");const provider=this.providers[input.provider];if(!provider)throw Error("PAYMENT_PROVIDER_UNAVAILABLE");const reference="OPPA_"+Date.now()+"_"+randomUUID().replaceAll("-","");const result=await provider.initialize({amountMinor:input.amountMinor,email:input.email,reference,callbackUrl:input.callbackUrl});return this.repo.create({userId:input.userId,provider:input.provider,reference,amountMinor:input.amountMinor,authorizationUrl:result.authorizationUrl})}
 async authorizeReversal(userId:string,proof:AuthorizationProof){if(!this.authorization)throw Error("SENSITIVE_AUTH_UNAVAILABLE");return this.authorization.authorize({userId,operation:"payment_reversal",proof})}
 async handleWebhook(providerName:"paystack"|"flutterwave",rawBody:Buffer,signature:string|undefined){const provider=this.providers[providerName];if(!provider||!provider.verifyWebhook(rawBody,signature))throw Error("PAYMENT_WEBHOOK_INVALID");let body:any;try{body=JSON.parse(rawBody.toString("utf8"))}catch{throw Error("PAYMENT_WEBHOOK_INVALID")}const reference=providerName==="paystack"?body?.data?.reference:body?.data?.tx_ref;if(typeof reference!=="string"||!/^[A-Za-z0-9._:-]{1,160}$/.test(reference))throw Error("PAYMENT_REFERENCE_INVALID");const verified=await provider.verify(reference);if(verified.reference!==reference||verified.currency!=="NGN")throw Error("PAYMENT_CURRENCY_INVALID");if(verified.status!=="success"){await this.repo.markFailed(providerName,reference);return{status:"failed"}}const existing=await this.repo.findByProviderReference(providerName,reference);if(!existing)throw Error("PAYMENT_NOT_FOUND");if(existing.status==="paid")return{status:"paid",payment:existing};const risk=evaluatePaymentRisk({amountMinor:verified.amountMinor,recentPaidCount:0,recentFailedCount:0});await this.repo.setRisk(existing.id,risk.score,risk.decision,risk.reasons);if(risk.decision!=="allow")throw Error(risk.decision==="block"?"PAYMENT_RISK_BLOCKED":"PAYMENT_REQUIRES_REVIEW");const payment=await this.repo.markPaidAndCredit({provider:providerName,reference,transactionId:verified.transactionId,amountMinor:verified.amountMinor});return{status:"paid",payment}}
}
