import type { ErrorRequestHandler } from "express";

const statuses: Record<string, number> = {
  FORBIDDEN: 403, USER_NOT_FOUND: 404, MESSAGE_BODY_REQUIRED: 400, MESSAGE_TOO_LONG: 413,
  PHONE_INVALID: 400, OTP_INVALID_OR_EXPIRED: 401, OTP_ATTEMPTS_EXCEEDED: 429,
  OTP_RATE_LIMITED: 429, OTP_ALREADY_ACTIVE: 429, ACCOUNT_UNAVAILABLE: 403,
  DEVICE_ID_INVALID: 400, DEVICE_KEY_INVALID: 400, PROFILE_FIELD_INVALID: 400,
  PROFILE_FIELD_TOO_LONG: 400, CONVERSATION_SELF_INVALID: 400, CONTACT_SELF_INVALID: 400,
  REFRESH_TOKEN_INVALID: 401, WALLET_AMOUNT_INVALID: 400, WALLET_BALANCE_INVALID: 500,
  WALLET_REFERENCE_INVALID: 400, WALLET_REFERENCE_REUSED: 409,
  WALLET_INSUFFICIENT_FUNDS: 409, WALLET_TRANSFER_SELF: 400, WALLET_LIMIT_INVALID: 400,
  WALLET_CURSOR_INVALID: 400, PAYMENT_PROVIDER_INVALID: 400, PAYMENT_PROVIDER_UNAVAILABLE: 503,
  PAYMENT_EMAIL_INVALID: 400, PAYMENT_REFERENCE_INVALID: 400, PAYMENT_AMOUNT_INVALID: 400,
  PAYMENT_CURRENCY_INVALID: 400, PAYMENT_NOT_FOUND: 404, PAYMENT_AMOUNT_MISMATCH: 409,
  PAYMENT_RISK_BLOCKED: 403, PAYMENT_REQUIRES_REVIEW: 409, PAYMENT_RISK_NOT_EVALUATED: 409,
  PAYMENT_TRANSACTION_MISMATCH: 409, PAYMENT_ALREADY_REVERSED: 409, PAYMENT_WEBHOOK_INVALID: 401,
  PAYMENT_WEBHOOK_BODY_MISSING: 400, SENSITIVE_OPERATION_INVALID: 400, SENSITIVE_AUTH_UNAVAILABLE: 503,
  DEVICE_NOT_ACTIVE: 403, DEVICE_PROOF_INVALID: 401, STEP_UP_INVALID: 401,
  STEP_UP_CHALLENGE_CONFLICT: 409, INTENT_INVALID: 400, INTENT_TOO_DEEP: 400,
  INTENT_TOO_LARGE: 400, INTENT_VALUE_INVALID: 400, PAYMENT_REVERSAL_REASON_INVALID: 400,
  PAYMENT_NOT_SETTLED: 409, PAYMENT_REVERSAL_ALREADY_EXISTS: 409, PAYMENT_STATE_RACE: 409,
  PAYMENT_REVERSAL_STATE_RACE: 409, WALLET_INSUFFICIENT_FUNDS_FOR_REVERSAL: 409,
  WALLET_TRANSFER_LIMIT_EXCEEDED: 409, WALLET_TRANSFER_BLOCKED: 409,
  USER_ID_REQUIRED: 400, RISK_PAGINATION_INVALID: 400, RISK_SERVICE_UNAVAILABLE: 503,
  RISK_CATEGORY_INVALID: 400, RISK_SIGNAL_INVALID: 400, RISK_SCORE_INVALID: 400,
  RISK_DECISION_INVALID: 400, RISK_SCOPE_INVALID: 400, RISK_REASON_INVALID: 400,
  RISK_EXPIRY_INVALID: 400
};

export const errorHandler: ErrorRequestHandler = (error, _req, res, _next) => {
  console.error("request_error", {
    name: error?.name,
    code: typeof error?.message === "string" ? error.message : "INTERNAL_SERVER_ERROR"
  });
  if (res.headersSent) return;
  const code = typeof error?.message === "string" && statuses[error.message]
    ? error.message : "INTERNAL_SERVER_ERROR";
  res.status(statuses[code] ?? 500).json({ error: code, requestId: res.locals.requestId });
};
