import assert from "node:assert/strict";
import { createHash, generateKeyPairSync, createSign } from "node:crypto";
import test from "node:test";
import { DeviceProofService } from "./device-proof-service.js";
import { canonicalizeIntent, hashIntent } from "./intent-binding.js";
function setup(intentHash:string|null=null){
 const {publicKey,privateKey}=generateKeyPairSync("ec",{namedCurve:"prime256v1"});
 const {privateKey:otherPrivateKey}=generateKeyPairSync("ec",{namedCurve:"prime256v1"});
 const calls:string[]=[];
 const repo:any={findActiveChallenge:async()=>({id:"c1",userId:"u1",deviceId:"d1",purpose:"wallet_transfer",challengeHash:hash("abc"),intentHash}),getActiveDevicePublicKey:async()=>publicKey,consumeChallenge:async()=>true,incrementChallengeAttempt:async(id:string)=>{calls.push(`attempt:${id}`)},recordEvent:async(input:any)=>{calls.push(`event:${input.metadata.reason??"verified"}`)}};
 return {repo,privateKey,otherPrivateKey,calls};
}
function sign(key:any,value:string){const s=createSign("SHA256");s.update(value);s.end();return s.sign(key).toString("base64url")}
function hash(value:string){return createHash("sha256").update(value).digest("hex")}
const intent={toUserId:"u2",amountMinor:50000,currency:"NGN",reference:"ref-1"};
test("accepts a valid device signature",async()=>{const {repo,privateKey,calls}=setup();assert.equal(await new DeviceProofService(repo).verify("u1","wallet_transfer",{deviceId:"d1",challenge:"abc",signature:sign(privateKey,"abc")}),true);assert.deepEqual(calls,["event:verified"])});
test("accepts a signature that covers challenge and bound intent",async()=>{const {repo,privateKey,calls}=setup(hashIntent(intent));const signed=`abc.${canonicalizeIntent(intent)}`;assert.equal(await new DeviceProofService(repo).verify("u1","wallet_transfer",{deviceId:"d1",challenge:"abc",signature:sign(privateKey,signed)},intent),true);assert.deepEqual(calls,["event:verified"])});
test("rejects a signature over only the challenge when intent is bound",async()=>{const {repo,privateKey,calls}=setup(hashIntent(intent));await assert.rejects(new DeviceProofService(repo).verify("u1","wallet_transfer",{deviceId:"d1",challenge:"abc",signature:sign(privateKey,"abc")},intent),{message:"DEVICE_PROOF_INVALID"});assert.deepEqual(calls,["attempt:c1","event:signature_invalid"])});
test("rejects a mismatched intent and records the failure",async()=>{const {repo,privateKey,calls}=setup(hashIntent(intent));await assert.rejects(new DeviceProofService(repo).verify("u1","wallet_transfer",{deviceId:"d1",challenge:"abc",signature:sign(privateKey,"abc")},{toUserId:"u3",amountMinor:1,currency:"NGN",reference:"ref-2"}),{message:"DEVICE_PROOF_INVALID"});assert.deepEqual(calls,["attempt:c1","event:intent_mismatch"])});
test("rejects a missing intent when one is bound",async()=>{const {repo,privateKey,calls}=setup(hashIntent(intent));await assert.rejects(new DeviceProofService(repo).verify("u1","wallet_transfer",{deviceId:"d1",challenge:"abc",signature:sign(privateKey,"abc")}),{message:"DEVICE_PROOF_INVALID"});assert.deepEqual(calls,["attempt:c1","event:intent_mismatch"])});
test("rejects an invalid signature and consumes an attempt",async()=>{const {repo,otherPrivateKey,calls}=setup();await assert.rejects(new DeviceProofService(repo).verify("u1","wallet_transfer",{deviceId:"d1",challenge:"abc",signature:sign(otherPrivateKey,"abc")}),{message:"DEVICE_PROOF_INVALID"});assert.deepEqual(calls,["attempt:c1","event:signature_invalid"])});
test("rejects a proof from a different device, incrementing attempts and recording an event",async()=>{const {repo,privateKey,calls}=setup();repo.findActiveChallenge=async()=>({id:"c1",userId:"u1",deviceId:"d2",purpose:"wallet_transfer",challengeHash:"x",intentHash:null});await assert.rejects(new DeviceProofService(repo).verify("u1","wallet_transfer",{deviceId:"d1",challenge:"abc",signature:sign(privateKey,"abc")}),{message:"DEVICE_PROOF_INVALID"});assert.deepEqual(calls,["attempt:c1","event:device_mismatch"])});
test("records an event when no active challenge exists",async()=>{const {repo,privateKey,calls}=setup();repo.findActiveChallenge=async()=>null;await assert.rejects(new DeviceProofService(repo).verify("u1","wallet_transfer",{deviceId:"d1",challenge:"abc",signature:sign(privateKey,"abc")}),{message:"DEVICE_PROOF_INVALID"});assert.deepEqual(calls,["event:challenge_not_found"])});
test("rejects a revoked device key and consumes an attempt",async()=>{const {repo,privateKey,calls}=setup();repo.getActiveDevicePublicKey=async()=>null;await assert.rejects(new DeviceProofService(repo).verify("u1","wallet_transfer",{deviceId:"d1",challenge:"abc",signature:sign(privateKey,"abc")}),{message:"DEVICE_PROOF_INVALID"});assert.deepEqual(calls,["attempt:c1","event:device_key_unavailable"])});